### ISSUE TITLE
Problem when trying to take screenshot

### ISSUE THREAD

**Issue by AgenChicken24** [jaimeadf/discord-screenshot#1]
So I am trying to use it in the gcphone that I have but when I try to take a screenshot I get this error but the sending images with screenshot-basic works fine I am using a PHP file that sends the photos to a folder but I can't figure it out 
![image](https://user-images.githubusercontent.com/64702468/96788528-542f3b80-13fc-11eb-9af3-353402c3e147.png)
 this is the error this is the code 
![image](https://user-images.githubusercontent.com/64702468/96788570-6315ee00-13fc-11eb-8892-34766e28925c.png)
and this is when I am trying to trigger it with the command 
![image](https://user-images.githubusercontent.com/64702468/96788629-7a54db80-13fc-11eb-9639-97ecdd9d1f0f.png)

**Comment by jaimeadf** [comment]
The first error is because the exports can only be called in the server.
The second one occurs because screenshot-basic uses http requests to send the image data to the server and FiveM blocks any request to localhost. You can bypass this connecting with your local ip adress that you can get typing ipconfig in a cmd.

![image](https://user-images.githubusercontent.com/40345645/96792588-10730c80-13d1-11eb-9939-f0a005456dc1.png)

**Comment by AgenChicken24** [comment]
Well ty. But I have to say that I am using gcphone and the sending images option works fine and it's on a local host using php and xamp. But I will try to call that function from server site. Ty for helping.

**Comment by AgenChicken24** [comment]
Ok I have moved the event to the server-side but I still get the error of blocking where do I change the IP because I tried to connect with my ipv4 address but still the same

**Comment by jaimeadf** [comment]
Can you add me in discord **Marmota#2533**?

**Comment by AgenChicken24** [comment]
I just did i am I'm a Chicken LOL#1819
